modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'manhunt_datapack', version = '1.0.2', displayName = '追杀指南针数据包 Manhunt Compass Datapack', logoFile= 'mh_icon.png', description = "1.20.5分支\n\n使用命令 /trigger mh.join.<队伍> 选择队伍\n使用命令 /function #mh:menu 查看设置界面", authors = 'Noryea' },
]
issueTrackerURL = 'https://github.com/Noryea/manhunt-datapack/issues'
