modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'manhunt_datapack', version = '1.0.1', displayName = '追杀指南针数据包 Manhunt Compass Datapack', logoFile= 'mh_icon.png', description = "一个还原猎人游戏玩法的数据包，兼容 1.21~1.21.4\n\n使用命令 /trigger mh.join.<队伍> 选择队伍\n使用命令 /function #mh:menu 查看设置界面", authors = 'Noryea' },
]
issueTrackerURL = 'https://github.com/Noryea/manhunt-datapack/issues'
