modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
	{ modId = 'manhunt_datapack', version = '1.0-alpha', displayName = '追杀指南针数据包 Manhunt Compass Datapack', description = "一个还原猎人游戏玩法的数据包，兼容 1.21~1.21.4", authors = 'Noryea' },
]
issueTrackerURL = 'https://github.com/Noryea/manhunt-datapack/issues'
